const fs = require("fs");

const dir = "C:/Users/Dell/Desktop/campus Os (1)/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/lib";
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

const code = [
'// ML tracking utility — runs entirely in browser using MediaPipe',
'// No Python or server needed',
'',
'export interface TrackingData {',
'  eyeContact: number;',
'  posture: number;',
'  confidence: number;',
'  expression: string;',
'  lookingAway: boolean;',
'  faceDetected: boolean;',
'  headTilt: number;',
'  multipleFaces: boolean;',
'}',
'',
'export interface InterviewMetrics {',
'  avgEyeContact: number;',
'  avgPosture: number;',
'  avgConfidence: number;',
'  lookAwayCount: number;',
'  totalSamples: number;',
'  expressionCounts: Record<string, number>;',
'  bodyLanguageScore: number;',
'}',
'',
'export function calculateMetrics(samples: TrackingData[]): InterviewMetrics {',
'  if (samples.length === 0) {',
'    return { avgEyeContact: 0, avgPosture: 0, avgConfidence: 0, lookAwayCount: 0, totalSamples: 0, expressionCounts: {}, bodyLanguageScore: 0 };',
'  }',
'  const avgEyeContact = Math.round(samples.reduce((s, d) => s + d.eyeContact, 0) / samples.length);',
'  const avgPosture = Math.round(samples.reduce((s, d) => s + d.posture, 0) / samples.length);',
'  const avgConfidence = Math.round(samples.reduce((s, d) => s + d.confidence, 0) / samples.length);',
'  const lookAwayCount = samples.filter(d => d.lookingAway).length;',
'  const expressionCounts: Record<string, number> = {};',
'  samples.forEach(d => { expressionCounts[d.expression] = (expressionCounts[d.expression] || 0) + 1; });',
'  const bodyLanguageScore = Math.round((avgEyeContact * 0.4) + (avgPosture * 0.3) + (avgConfidence * 0.3));',
'  return { avgEyeContact, avgPosture, avgConfidence, lookAwayCount, totalSamples: samples.length, expressionCounts, bodyLanguageScore };',
'}',
'',
'// Analyze face landmarks from MediaPipe to extract metrics',
'export function analyzeFaceLandmarks(landmarks: any[]): TrackingData {',
'  if (!landmarks || landmarks.length === 0) {',
'    return { eyeContact: 0, posture: 0, confidence: 50, expression: "neutral", lookingAway: true, faceDetected: false, headTilt: 0, multipleFaces: false };',
'  }',
'',
'  const pts = landmarks;',
'',
'  // Eye contact — check if eyes are looking forward',
'  // Left eye: landmarks 33, 133 | Right eye: 362, 263',
'  // Nose tip: 1 | Nose bridge: 168',
'  const noseTip = pts[1];',
'  const noseBridge = pts[168];',
'  const leftEye = pts[33];',
'  const rightEye = pts[263];',
'  const chin = pts[152];',
'  const forehead = pts[10];',
'',
'  // Head yaw (left-right rotation)',
'  const eyeCenter = { x: (leftEye.x + rightEye.x) / 2, y: (leftEye.y + rightEye.y) / 2 };',
'  const noseOffset = noseTip.x - eyeCenter.x;',
'  const yawAngle = Math.abs(noseOffset) * 100;',
'',
'  // Head pitch (up-down rotation)',
'  const faceHeight = Math.abs(forehead.y - chin.y);',
'  const noseVerticalPos = (noseTip.y - forehead.y) / faceHeight;',
'  const pitchAngle = Math.abs(noseVerticalPos - 0.55) * 100;',
'',
'  // Eye contact score — lower yaw and pitch = better eye contact',
'  const eyeContactRaw = Math.max(0, 100 - (yawAngle * 2.5) - (pitchAngle * 1.5));',
'  const eyeContact = Math.min(100, Math.round(eyeContactRaw));',
'',
'  // Looking away if yaw > 15 degrees equivalent',
'  const lookingAway = yawAngle > 15 || pitchAngle > 20;',
'',
'  // Head tilt (roll)',',
'  const dx = rightEye.x - leftEye.x;',
'  const dy = rightEye.y - leftEye.y;',
'  const headTilt = Math.round(Math.atan2(dy, dx) * (180 / Math.PI));',
'',
'  // Posture estimate from head position in frame',
'  // Good posture = face centered and upright',
'  const tiltPenalty = Math.abs(headTilt) * 2;',
'  const centerX = noseTip.x; // 0 to 1, 0.5 is center',
'  const centerPenalty = Math.abs(centerX - 0.5) * 60;',
'  const posture = Math.max(20, Math.min(100, Math.round(90 - tiltPenalty - centerPenalty)));',
'',
'  // Confidence from face size and stability',
'  const faceWidth = Math.abs(rightEye.x - leftEye.x);',
'  const confidenceFromSize = Math.min(100, Math.round(faceWidth * 800));',
'  const confidence = Math.max(20, confidenceFromSize);',
'',
'  // Expression from mouth openness',
'  const upperLip = pts[13];',
'  const lowerLip = pts[14];',
'  const mouthOpen = Math.abs(upperLip.y - lowerLip.y) * 100;',
'  let expression = "neutral";',
'  if (mouthOpen > 3) expression = "speaking";',
'  else if (eyeContact > 70 && confidence > 60) expression = "confident";',
'  else if (eyeContact < 40) expression = "nervous";',
'  else expression = "focused";',
'',
'  return { eyeContact, posture, confidence, expression, lookingAway, faceDetected: true, headTilt, multipleFaces: false };',
'}',
].join("\n");

fs.writeFileSync(dir + "/ml-tracking.ts", code, "utf8");
console.log("ml-tracking.ts created!");
