const fs = require("fs");
const path = "C:/Users/Dell/Desktop/campus Os (1)/campus Os/2026-04-20-you-are-a-senior-full-stack-2/apps/web/src/app/mock-interview/page.tsx";

const lines = [];
lines.push('"use client";');
lines.push('import { useState, useRef, useEffect, useCallback } from "react";');
lines.push('import { AppShell } from "@/components/app/app-shell";');
lines.push('import { Send, RotateCcw, ChevronRight, Trophy, Brain, AlertCircle, CheckCircle, Clock, User, Bot, Camera, CameraOff, Eye, EyeOff, Activity, TrendingUp, Award, Video } from "lucide-react";');
lines.push('import { analyzeFaceLandmarks, calculateMetrics, TrackingData, InterviewMetrics } from "@/lib/ml-tracking";');
lines.push('');
lines.push('const GROQ_KEY = process.env.NEXT_PUBLIC_GROQ_API_KEY;');
lines.push('');
lines.push('const DOMAINS = [');
lines.push('  { id: "frontend", label: "Frontend Developer", icon: "??", desc: "React, JS, CSS, HTML, DOM" },');
lines.push('  { id: "backend", label: "Backend Developer", icon: "??", desc: "Node.js, APIs, Databases, Server" },');
lines.push('  { id: "fullstack", label: "Full Stack Developer", icon: "??", desc: "MERN Stack, System Design" },');
lines.push('  { id: "python", label: "Python Developer", icon: "??", desc: "Python, Django, Flask, OOP" },');
lines.push('  { id: "dsa", label: "DSA & Problem Solving", icon: "??", desc: "Arrays, Trees, DP, Graphs" },');
lines.push('  { id: "datascience", label: "Data Science / ML", icon: "??", desc: "ML, Python, NumPy, Pandas" },');
lines.push('  { id: "devops", label: "DevOps / Cloud", icon: "??", desc: "Docker, AWS, CI/CD, Linux" },');
lines.push('  { id: "dbms", label: "Database & SQL", icon: "???", desc: "SQL, MongoDB, Indexing, Joins" },');
lines.push('  { id: "os", label: "Operating Systems", icon: "??", desc: "Process, Memory, Scheduling" },');
lines.push('  { id: "cn", label: "Computer Networks", icon: "??", desc: "TCP/IP, HTTP, OSI Model, DNS" },');
lines.push('];');
lines.push('');
lines.push('async function callGroq(messages) {');
lines.push('  const res = await fetch("https://api.groq.com/openai/v1/chat/completions", {');
lines.push('    method: "POST",');
lines.push('    headers: { "Content-Type": "application/json", "Authorization": "Bearer " + GROQ_KEY },');
lines.push('    body: JSON.stringify({ model: "llama-3.3-70b-versatile", messages, max_tokens: 1024 }),');
lines.push('  });');
lines.push('  const data = await res.json();');
lines.push('  if (data.error) throw new Error(data.error.message);');
lines.push('  return data.choices[0].message.content;');
lines.push('}');
lines.push('');
lines.push('// Live metric display widget');
lines.push('function MetricBadge({ label, value, color }: { label: string; value: number; color: string }) {');
lines.push('  const bgMap = { green: "bg-green-500/15 border-green-500/30 text-green-500", amber: "bg-amber-500/15 border-amber-500/30 text-amber-500", red: "bg-red-500/15 border-red-500/30 text-red-500", blue: "bg-blue-500/15 border-blue-500/30 text-blue-500" };');
lines.push('  return (');
lines.push('    <div className={"flex flex-col items-center border rounded-xl px-3 py-2 min-w-[70px] " + (bgMap[color] || bgMap.blue)}>');
lines.push('      <span className="text-xl font-black leading-none">{value}%</span>');
lines.push('      <span className="text-xs font-medium mt-0.5 opacity-80">{label}</span>');
lines.push('    </div>');
lines.push('  );');
lines.push('}');
lines.push('');
lines.push('export default function MockInterviewPage() {');
lines.push('  const [phase, setPhase] = useState("select");');
lines.push('  const [domain, setDomain] = useState<any>(null);');
lines.push('  const [messages, setMessages] = useState<any[]>([]);');
lines.push('  const [answer, setAnswer] = useState("");');
lines.push('  const [loading, setLoading] = useState(false);');
lines.push('  const [qCount, setQCount] = useState(0);');
lines.push('  const [timer, setTimer] = useState(0);');
lines.push('  const [report, setReport] = useState<any>(null);');
lines.push('  const [cameraOn, setCameraOn] = useState(false);');
lines.push('  const [cameraError, setCameraError] = useState("");');
lines.push('  const [tracking, setTracking] = useState<TrackingData | null>(null);');
lines.push('  const [mlSamples, setMlSamples] = useState<TrackingData[]>([]);');
lines.push('  const [mlMetrics, setMlMetrics] = useState<InterviewMetrics | null>(null);');
lines.push('  const [mlReady, setMlReady] = useState(false);');
lines.push('  const [mlLoading, setMlLoading] = useState(false);');
lines.push('  const [showOverlay, setShowOverlay] = useState(true);');
lines.push('');
lines.push('  const videoRef = useRef<HTMLVideoElement>(null);');
lines.push('  const canvasRef = useRef<HTMLCanvasElement>(null);');
lines.push('  const chatRef = useRef<HTMLDivElement>(null);');
lines.push('  const timerRef = useRef<any>(null);');
lines.push('  const mlIntervalRef = useRef<any>(null);');
lines.push('  const streamRef = useRef<MediaStream | null>(null);');
lines.push('  const faceMeshRef = useRef<any>(null);');
lines.push('  const MAX_Q = 7;');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    if (chatRef.current) chatRef.current.scrollTop = chatRef.current.scrollHeight;');
lines.push('  }, [messages]);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    if (phase === "interview") {');
lines.push('      timerRef.current = setInterval(() => setTimer(t => t + 1), 1000);');
lines.push('    } else {');
lines.push('      clearInterval(timerRef.current);');
lines.push('    }');
lines.push('    return () => clearInterval(timerRef.current);');
lines.push('  }, [phase]);');
lines.push('');
lines.push('  // Load MediaPipe FaceMesh');
lines.push('  const loadFaceMesh = useCallback(async () => {');
lines.push('    setMlLoading(true);');
lines.push('    try {');
lines.push('      const script1 = document.createElement("script");');
lines.push('      script1.src = "https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/face_mesh.js";');
lines.push('      script1.crossOrigin = "anonymous";');
lines.push('      document.head.appendChild(script1);');
lines.push('      await new Promise(r => { script1.onload = r; script1.onerror = r; });');
lines.push('');
lines.push('      await new Promise(r => setTimeout(r, 1000));');
lines.push('');
lines.push('      if ((window as any).FaceMesh) {');
lines.push('        const fm = new (window as any).FaceMesh({');
lines.push('          locateFile: (f: string) => `https://cdn.jsdelivr.net/npm/@mediapipe/face_mesh/${f}`');
lines.push('        });');
lines.push('        fm.setOptions({ maxNumFaces: 1, refineLandmarks: true, minDetectionConfidence: 0.5, minTrackingConfidence: 0.5 });');
lines.push('        fm.onResults((results: any) => {');
lines.push('          if (results.multiFaceLandmarks && results.multiFaceLandmarks.length > 0) {');
lines.push('            const landmarks = results.multiFaceLandmarks[0];');
lines.push('            const data = analyzeFaceLandmarks(landmarks);');
lines.push('            setTracking(data);');
lines.push('            setMlSamples(prev => [...prev, data]);');
lines.push('            drawOverlay(landmarks);');
lines.push('          } else {');
lines.push('            setTracking({ eyeContact: 0, posture: 50, confidence: 50, expression: "not detected", lookingAway: true, faceDetected: false, headTilt: 0, multipleFaces: false });');
lines.push('          }');
lines.push('        });');
lines.push('        faceMeshRef.current = fm;');
lines.push('        setMlReady(true);');
lines.push('      }');
lines.push('    } catch (e) {');
lines.push('      console.log("MediaPipe load error:", e);');
lines.push('    }');
lines.push('    setMlLoading(false);');
lines.push('  }, []);');
lines.push('');
lines.push('  // Draw face overlay on canvas');
lines.push('  const drawOverlay = useCallback((landmarks: any[]) => {');
lines.push('    const canvas = canvasRef.current;');
lines.push('    const video = videoRef.current;');
lines.push('    if (!canvas || !video || !showOverlay) return;');
lines.push('    const ctx = canvas.getContext("2d");');
lines.push('    if (!ctx) return;');
lines.push('    canvas.width = video.videoWidth || 320;');
lines.push('    canvas.height = video.videoHeight || 240;');
lines.push('    ctx.clearRect(0, 0, canvas.width, canvas.height);');
lines.push('');
lines.push('    // Draw face mesh dots');
lines.push('    ctx.fillStyle = "rgba(99, 255, 200, 0.6)";');
lines.push('    landmarks.forEach((pt: any) => {');
lines.push('      ctx.beginPath();');
lines.push('      ctx.arc(pt.x * canvas.width, pt.y * canvas.height, 1.2, 0, 2 * Math.PI);');
lines.push('      ctx.fill();');
lines.push('    });');
lines.push('');
lines.push('    // Draw eye highlight boxes');
lines.push('    const eyePoints = [33, 133, 362, 263, 159, 145, 386, 374];');
lines.push('    ctx.strokeStyle = "rgba(99, 200, 255, 0.8)";');
lines.push('    ctx.lineWidth = 1.5;');
lines.push('    // Left eye box');
lines.push('    const leX = landmarks[33].x * canvas.width;');
lines.push('    const leY = landmarks[159].y * canvas.height;');
lines.push('    const leW = (landmarks[133].x - landmarks[33].x) * canvas.width;');
lines.push('    const leH = (landmarks[145].y - landmarks[159].y) * canvas.height;');
lines.push('    ctx.strokeRect(leX - 5, leY - 5, Math.abs(leW) + 10, Math.abs(leH) + 10);');
lines.push('    // Right eye box');
lines.push('    const reX = landmarks[362].x * canvas.width;');
lines.push('    const reY = landmarks[386].y * canvas.height;');
lines.push('    const reW = (landmarks[263].x - landmarks[362].x) * canvas.width;');
lines.push('    const reH = (landmarks[374].y - landmarks[386].y) * canvas.height;');
lines.push('    ctx.strokeRect(reX - 5, reY - 5, Math.abs(reW) + 10, Math.abs(reH) + 10);');
lines.push('  }, [showOverlay]);');
lines.push('');
lines.push('  // Start camera');
lines.push('  const startCamera = useCallback(async () => {');
lines.push('    setCameraError("");');
lines.push('    try {');
lines.push('      const stream = await navigator.mediaDevices.getUserMedia({ video: { width: 320, height: 240, facingMode: "user" }, audio: false });');
lines.push('      streamRef.current = stream;');
lines.push('      if (videoRef.current) {');
lines.push('        videoRef.current.srcObject = stream;');
lines.push('        videoRef.current.play();');
lines.push('      }');
lines.push('      setCameraOn(true);');
lines.push('      if (!mlReady) await loadFaceMesh();');
lines.push('      // Start processing frames');
lines.push('      mlIntervalRef.current = setInterval(async () => {');
lines.push('        if (faceMeshRef.current && videoRef.current && videoRef.current.readyState >= 2) {');
lines.push('          try { await faceMeshRef.current.send({ image: videoRef.current }); } catch {}');
lines.push('        }');
lines.push('      }, 200);');
lines.push('    } catch (e: any) {');
lines.push('      setCameraError("Camera access denied. Please allow camera permission in browser settings.");');
lines.push('      setCameraOn(false);');
lines.push('    }');
lines.push('  }, [mlReady, loadFaceMesh]);');
lines.push('');
lines.push('  // Stop camera');
lines.push('  const stopCamera = useCallback(() => {');
lines.push('    clearInterval(mlIntervalRef.current);');
lines.push('    if (streamRef.current) {');
lines.push('      streamRef.current.getTracks().forEach(t => t.stop());');
lines.push('      streamRef.current = null;');
lines.push('    }');
lines.push('    if (videoRef.current) videoRef.current.srcObject = null;');
lines.push('    setCameraOn(false);');
lines.push('    setTracking(null);');
lines.push('  }, []);');
lines.push('');
lines.push('  useEffect(() => {');
lines.push('    return () => { stopCamera(); };');
lines.push('  }, [stopCamera]);');
lines.push('');
lines.push('  const fmt = (s: number) => {');
lines.push('    const m = Math.floor(s / 60).toString().padStart(2, "0");');
lines.push('    const sec = (s % 60).toString().padStart(2, "0");');
lines.push('    return m + ":" + sec;');
lines.push('  };');
lines.push('');
lines.push('  const startInterview = async (d: any) => {');
lines.push('    setDomain(d);');
lines.push('    setPhase("interview");');
lines.push('    setLoading(true);');
lines.push('    setQCount(1);');
lines.push('    setTimer(0);');
lines.push('    setMlSamples([]);');
lines.push('    const sys = "You are a strict but supportive technical interviewer for a " + d.label + " role. Ask one clear technical question at a time. Give brief feedback after each answer then ask next question. Topics: " + d.desc + ". Increase difficulty gradually.";');
lines.push('    const first = await callGroq([{ role: "system", content: sys }, { role: "user", content: "Start the interview with your first question." }]);');
lines.push('    setMessages([{ role: "system", content: sys }, { role: "assistant", content: first }]);');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const sendAnswer = async () => {');
lines.push('    if (!answer.trim() || loading) return;');
lines.push('    const userMsg = { role: "user", content: answer };');
lines.push('    const newMsgs = [...messages, userMsg];');
lines.push('    setMessages(newMsgs);');
lines.push('    setAnswer("");');
lines.push('    setLoading(true);');
lines.push('    const nextQ = qCount + 1;');
lines.push('    setQCount(nextQ);');
lines.push('    if (nextQ > MAX_Q) {');
lines.push('      const metrics = calculateMetrics(mlSamples);');
lines.push('      setMlMetrics(metrics);');
lines.push('      const bodyInfo = cameraOn ? " Body language data: Eye contact " + metrics.avgEyeContact + "%, Posture " + metrics.avgPosture + "%, Confidence " + metrics.avgConfidence + "%, Looked away " + metrics.lookAwayCount + " times." : "";');
lines.push('      const finalPrompt = [...newMsgs, { role: "user", content: "Interview complete. Give detailed report in this exact JSON, no extra text: {\\"score\\":75,\\"grade\\":\\"B+\\",\\"verdict\\":\\"summary\\",\\"strengths\\":[\\"s1\\",\\"s2\\",\\"s3\\"],\\"weaknesses\\":[\\"w1\\",\\"w2\\"],\\"tips\\":[\\"t1\\",\\"t2\\",\\"t3\\"],\\"topic_scores\\":[{\\"topic\\":\\"name\\",\\"score\\":80}],\\"next_steps\\":\\"what to study\\"}" + bodyInfo }];');
lines.push('      try {');
lines.push('        const raw = await callGroq(finalPrompt);');
lines.push('        setReport(JSON.parse(raw.replace(/```json/g, "").replace(/```/g, "").trim()));');
lines.push('      } catch {');
lines.push('        setReport({ score: 70, grade: "B", verdict: "Good effort!", strengths: ["Attempted all questions"], weaknesses: ["Need more depth"], tips: ["Practice daily"], topic_scores: [{ topic: d.label, score: 70 }], next_steps: "Keep practicing" });');
lines.push('      }');
lines.push('      stopCamera();');
lines.push('      setPhase("report");');
lines.push('    } else {');
lines.push('      const reply = await callGroq(newMsgs);');
lines.push('      setMessages((m: any[]) => [...m, { role: "assistant", content: reply }]);');
lines.push('    }');
lines.push('    setLoading(false);');
lines.push('  };');
lines.push('');
lines.push('  const reset = () => {');
lines.push('    stopCamera();');
lines.push('    setPhase("select"); setDomain(null); setMessages([]);');
lines.push('    setAnswer(""); setQCount(0); setTimer(0); setReport(null);');
lines.push('    setMlSamples([]); setMlMetrics(null); setTracking(null);');
lines.push('  };');
lines.push('');
lines.push('  const getMetricColor = (v: number) => v >= 70 ? "green" : v >= 40 ? "amber" : "red";');
lines.push('  const visibleMsgs = messages.filter((m: any) => m.role !== "system");');
lines.push('');
lines.push('  return (');
lines.push('    <AppShell activePath="/mock-interview">');
lines.push('      <div className="space-y-5">');
lines.push('');
lines.push('        {phase === "select" && (');
lines.push('          <div className="space-y-5">');
lines.push('            <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('              <div className="flex items-center gap-3 mb-4">');
lines.push('                <div className="w-12 h-12 rounded-2xl bg-violet-500/15 border border-violet-500/20 flex items-center justify-center flex-shrink-0">');
lines.push('                  <Brain className="w-6 h-6 text-violet-500" />');
lines.push('                </div>');
lines.push('                <div>');
lines.push('                  <h1 className="text-xl font-bold text-slate-900 dark:text-white">AI Video Mock Interview</h1>');
lines.push('                  <p className="text-slate-500 text-xs mt-0.5">Real-time face tracking + AI questions + body language analysis</p>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">');
lines.push('                {[["7", "Questions", "violet"], ["Camera", "ML Tracking", "blue"], ["Face Mesh", "468 Points", "cyan"], ["Full Report", "AI + Body Lang", "green"]].map(([v, l, c]) => (');
lines.push('                  <div key={l} className={"rounded-2xl p-3 border text-center " + (c === "violet" ? "bg-violet-500/5 border-violet-500/20" : c === "blue" ? "bg-blue-500/5 border-blue-500/20" : c === "cyan" ? "bg-cyan-500/5 border-cyan-500/20" : "bg-green-500/5 border-green-500/20")}>');
lines.push('                    <div className={"font-black text-lg " + (c === "violet" ? "text-violet-500" : c === "blue" ? "text-blue-500" : c === "cyan" ? "text-cyan-500" : "text-green-500")}>{v}</div>');
lines.push('                    <div className="text-slate-400 text-xs mt-0.5">{l}</div>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('              <div className="mt-4 bg-blue-500/5 border border-blue-500/20 rounded-2xl p-4">');
lines.push('                <p className="text-blue-600 dark:text-blue-400 text-sm font-semibold mb-2 flex items-center gap-2"><Video className="w-4 h-4" />What gets tracked in real-time:</p>');
lines.push('                <div className="grid md:grid-cols-2 gap-2">');
lines.push('                  {["??? Eye contact — are you looking at camera", "?? Posture — head position and tilt", "?? Facial expression — confident/nervous/focused", "?? Live confidence score updated every 200ms", "?? Look-away count — how often you look away", "?? Final body language score included in report"].map(item => (');
lines.push('                    <div key={item} className="text-slate-600 dark:text-slate-400 text-xs flex items-start gap-1">');
lines.push('                      <span>{item}</span>');
lines.push('                    </div>');
lines.push('                  ))}');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('            <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 p-6 dark:border-white/10 dark:bg-white/5">');
lines.push('              <h2 className="text-slate-900 dark:text-white font-bold mb-4">Select Your Domain</h2>');
lines.push('              <div className="grid md:grid-cols-2 gap-3">');
lines.push('                {DOMAINS.map((d: any) => (');
lines.push('                  <button key={d.id} onClick={() => startInterview(d)}');
lines.push('                    className="flex items-center gap-3 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-4 hover:border-violet-500/40 hover:bg-violet-500/5 transition-all group text-left">');
lines.push('                    <span className="text-2xl">{d.icon}</span>');
lines.push('                    <div className="flex-1 min-w-0">');
lines.push('                      <div className="text-slate-800 dark:text-white font-semibold text-sm">{d.label}</div>');
lines.push('                      <div className="text-slate-400 text-xs mt-0.5">{d.desc}</div>');
lines.push('                    </div>');
lines.push('                    <ChevronRight className="w-4 h-4 text-slate-300 group-hover:text-violet-500 transition-colors flex-shrink-0" />');
lines.push('                  </button>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('');
lines.push('        {phase === "interview" && (');
lines.push('          <div className="grid lg:grid-cols-[1fr_320px] gap-5">');
lines.push('');
lines.push('            <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 dark:border-white/10 dark:bg-white/5 overflow-hidden flex flex-col">');
lines.push('              <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200 dark:border-white/10">');
lines.push('                <div className="flex items-center gap-3">');
lines.push('                  <span className="text-xl">{domain?.icon}</span>');
lines.push('                  <div>');
lines.push('                    <div className="text-slate-900 dark:text-white font-bold text-sm">{domain?.label}</div>');
lines.push('                    <div className="text-slate-400 text-xs">Q {Math.min(qCount, MAX_Q)} / {MAX_Q}</div>');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('                <div className="flex items-center gap-2">');
lines.push('                  <div className="flex items-center gap-1.5 bg-slate-100 dark:bg-white/5 px-3 py-1.5 rounded-xl">');
lines.push('                    <Clock className="w-3.5 h-3.5 text-slate-400" />');
lines.push('                    <span className="text-slate-600 dark:text-slate-300 text-sm font-mono">{fmt(timer)}</span>');
lines.push('                  </div>');
lines.push('                  <div className="flex gap-1">');
lines.push('                    {Array.from({ length: MAX_Q }).map((_, i) => (');
lines.push('                      <div key={i} className={"w-2 h-2 rounded-full " + (i < qCount - 1 ? "bg-violet-500" : i === qCount - 1 ? "bg-violet-500 animate-pulse" : "bg-slate-200 dark:bg-white/10")} />');
lines.push('                    ))}');
lines.push('                  </div>');
lines.push('                  <button onClick={reset} className="p-1.5 text-slate-400 hover:text-red-500 rounded-lg hover:bg-red-500/10 transition-all">');
lines.push('                    <RotateCcw className="w-4 h-4" />');
lines.push('                  </button>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('');
lines.push('              <div ref={chatRef} className="flex-1 overflow-y-auto p-5 space-y-4 min-h-[300px] max-h-[400px]">');
lines.push('                {visibleMsgs.map((msg: any, i: number) => (');
lines.push('                  <div key={i} className={"flex gap-3 " + (msg.role === "user" ? "flex-row-reverse" : "")}>');
lines.push('                    <div className={"w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 " + (msg.role === "assistant" ? "bg-violet-500/20 border border-violet-500/30" : "bg-cyan-500/20 border border-cyan-500/30")}>');
lines.push('                      {msg.role === "assistant" ? <Bot className="w-4 h-4 text-violet-500" /> : <User className="w-4 h-4 text-cyan-500" />}');
lines.push('                    </div>');
lines.push('                    <div className={"max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-relaxed " + (msg.role === "assistant" ? "bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-300 rounded-tl-sm" : "bg-violet-600 text-white rounded-tr-sm")}>');
lines.push('                      {msg.content}');
lines.push('                    </div>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('                {loading && (');
lines.push('                  <div className="flex gap-3">');
lines.push('                    <div className="w-8 h-8 rounded-full bg-violet-500/20 border border-violet-500/30 flex items-center justify-center">');
lines.push('                      <Bot className="w-4 h-4 text-violet-500" />');
lines.push('                    </div>');
lines.push('                    <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl px-4 py-3 flex gap-1">');
lines.push('                      {[0,150,300].map(d => <div key={d} className="w-2 h-2 bg-violet-400 rounded-full animate-bounce" style={{ animationDelay: d + "ms" }} />)}');
lines.push('                    </div>');
lines.push('                  </div>');
lines.push('                )}');
lines.push('              </div>');
lines.push('');
lines.push('              <div className="border-t border-slate-200 dark:border-white/10 p-4">');
lines.push('                <div className="flex gap-3">');
lines.push('                  <textarea rows={2} value={answer} onChange={e => setAnswer(e.target.value)}');
lines.push('                    onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendAnswer(); } }}');
lines.push('                    placeholder="Type your answer... (Enter to submit)"');
lines.push('                    disabled={loading}');
lines.push('                    className="flex-1 bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl px-4 py-3 text-sm resize-none focus:outline-none focus:border-violet-500 transition-colors disabled:opacity-50 text-slate-700 dark:text-slate-300" />');
lines.push('                  <button onClick={sendAnswer} disabled={loading || !answer.trim()}');
lines.push('                    className="w-12 h-12 bg-violet-600 hover:bg-violet-500 disabled:opacity-40 text-white rounded-2xl flex items-center justify-center self-end transition-all">');
lines.push('                    <Send className="w-4 h-4" />');
lines.push('                  </button>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            </div>');
lines.push('');
lines.push('            <div className="space-y-4">');
lines.push('              <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 dark:border-white/10 dark:bg-white/5 overflow-hidden">');
lines.push('                <div className="px-4 py-3 border-b border-slate-200 dark:border-white/10 flex items-center justify-between">');
lines.push('                  <span className="text-slate-700 dark:text-white font-semibold text-sm flex items-center gap-2"><Camera className="w-4 h-4 text-violet-500" />Camera Feed</span>');
lines.push('                  <div className="flex gap-2">');
lines.push('                    <button onClick={() => setShowOverlay(!showOverlay)} className="text-xs px-2.5 py-1 rounded-lg border border-slate-200 dark:border-white/10 text-slate-500 hover:border-violet-500/30 transition-all">');
lines.push('                      {showOverlay ? <Eye className="w-3.5 h-3.5" /> : <EyeOff className="w-3.5 h-3.5" />}');
lines.push('                    </button>');
lines.push('                    <button onClick={cameraOn ? stopCamera : startCamera}');
lines.push('                      className={"text-xs px-3 py-1 rounded-lg font-semibold transition-all " + (cameraOn ? "bg-red-500/15 text-red-500 border border-red-500/20 hover:bg-red-500/25" : "bg-violet-500/15 text-violet-500 border border-violet-500/20 hover:bg-violet-500/25")}>');
lines.push('                      {cameraOn ? "Stop" : "Start"}');
lines.push('                    </button>');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('');
lines.push('                <div className="relative bg-slate-900 aspect-video">');
lines.push('                  <video ref={videoRef} className="w-full h-full object-cover" autoPlay muted playsInline />');
lines.push('                  <canvas ref={canvasRef} className={"absolute inset-0 w-full h-full " + (showOverlay ? "opacity-100" : "opacity-0")} style={{ pointerEvents: "none" }} />');
lines.push('');
lines.push('                  {!cameraOn && (');
lines.push('                    <div className="absolute inset-0 flex flex-col items-center justify-center bg-slate-900">');
lines.push('                      <CameraOff className="w-10 h-10 text-slate-600 mb-3" />');
lines.push('                      <p className="text-slate-400 text-xs text-center px-4">Click Start to enable camera and ML tracking</p>');
lines.push('                      {cameraError && <p className="text-red-400 text-xs mt-2 text-center px-4">{cameraError}</p>}');
lines.push('                    </div>');
lines.push('                  )}');
lines.push('');
lines.push('                  {cameraOn && mlLoading && (');
lines.push('                    <div className="absolute inset-0 flex items-center justify-center bg-slate-900/80">');
lines.push('                      <div className="text-center">');
lines.push('                        <div className="w-8 h-8 border-2 border-violet-500 border-t-transparent rounded-full animate-spin mx-auto mb-2" />');
lines.push('                        <p className="text-white text-xs">Loading ML model...</p>');
lines.push('                      </div>');
lines.push('                    </div>');
lines.push('                  )}');
lines.push('');
lines.push('                  {cameraOn && !mlLoading && tracking && (');
lines.push('                    <div className="absolute top-2 left-2 right-2 flex flex-wrap gap-1">');
lines.push('                      {tracking.faceDetected ? (');
lines.push('                        <span className="text-xs bg-green-500/90 text-white px-2 py-0.5 rounded-full font-semibold">Face Detected</span>');
lines.push('                      ) : (');
lines.push('                        <span className="text-xs bg-red-500/90 text-white px-2 py-0.5 rounded-full font-semibold animate-pulse">No Face</span>');
lines.push('                      )}');
lines.push('                      {tracking.lookingAway && <span className="text-xs bg-amber-500/90 text-white px-2 py-0.5 rounded-full font-semibold">Look at camera</span>}');
lines.push('                      <span className="text-xs bg-slate-800/90 text-white px-2 py-0.5 rounded-full">{tracking.expression}</span>');
lines.push('                    </div>');
lines.push('                  )}');
lines.push('                </div>');
lines.push('              </div>');
lines.push('');
lines.push('              {cameraOn && tracking && tracking.faceDetected && (');
lines.push('                <div className="rounded-[2rem] border border-slate-200/80 bg-white/70 dark:border-white/10 dark:bg-white/5 p-4">');
lines.push('                  <div className="flex items-center gap-2 mb-3">');
lines.push('                    <Activity className="w-4 h-4 text-violet-500" />');
lines.push('                    <span className="text-slate-700 dark:text-white font-semibold text-sm">Live Tracking</span>');
lines.push('                    <span className="ml-auto w-2 h-2 bg-green-400 rounded-full animate-pulse" />');
lines.push('                  </div>');
lines.push('                  <div className="grid grid-cols-3 gap-2">');
lines.push('                    <MetricBadge label="Eye Contact" value={tracking.eyeContact} color={getMetricColor(tracking.eyeContact)} />');
lines.push('                    <MetricBadge label="Posture" value={tracking.posture} color={getMetricColor(tracking.posture)} />');
lines.push('                    <MetricBadge label="Confidence" value={tracking.confidence} color={getMetricColor(tracking.confidence)} />');
lines.push('                  </div>');
lines.push('                  <div className="mt-3 space-y-2">');
lines.push('                    {[{ label: "Eye Contact", val: tracking.eyeContact }, { label: "Posture", val: tracking.posture }, { label: "Confidence", val: tracking.confidence }].map(({ label, val }) => (');
lines.push('                      <div key={label}>');
lines.push('                        <div className="flex justify-between text-xs mb-1">');
lines.push('                          <span className="text-slate-500">{label}</span>');
lines.push('                          <span className={"font-semibold " + (val >= 70 ? "text-green-500" : val >= 40 ? "text-amber-500" : "text-red-500")}>{val}%</span>');
lines.push('                        </div>');
lines.push('                        <div className="w-full h-1.5 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">');
lines.push('                          <div className={"h-full rounded-full transition-all duration-300 " + (val >= 70 ? "bg-green-500" : val >= 40 ? "bg-amber-500" : "bg-red-500")} style={{ width: val + "%" }} />');
lines.push('                        </div>');
lines.push('                      </div>');
lines.push('                    ))}');
lines.push('                  </div>');
lines.push('                  <div className="mt-3 text-xs text-slate-400 text-center">Samples collected: {mlSamples.length}</div>');
lines.push('                </div>');
lines.push('              )}');
lines.push('');
lines.push('              {!cameraOn && (');
lines.push('                <div className="rounded-2xl border border-amber-500/20 bg-amber-500/5 p-4">');
lines.push('                  <p className="text-amber-600 dark:text-amber-400 text-xs font-semibold mb-1">Camera optional</p>');
lines.push('                  <p className="text-slate-500 text-xs">Enable camera for body language analysis. Interview works without it too.</p>');
lines.push('                </div>');
lines.push('              )}');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('');
lines.push('        {phase === "report" && report && (');
lines.push('          <div className="space-y-5">');
lines.push('');
lines.push('            <div className={"rounded-[2rem] border-2 p-8 text-center " + (report.score >= 75 ? "border-green-500/30 bg-green-500/5" : report.score >= 50 ? "border-amber-500/30 bg-amber-500/5" : "border-red-500/30 bg-red-500/5")}>');
lines.push('              <Trophy className={"w-12 h-12 mx-auto mb-3 " + (report.score >= 75 ? "text-green-500" : report.score >= 50 ? "text-amber-500" : "text-red-500")} />');
lines.push('              <div className={"text-8xl font-black mb-1 " + (report.score >= 75 ? "text-green-500" : report.score >= 50 ? "text-amber-500" : "text-red-500")}>{report.score}</div>');
lines.push('              <div className="text-slate-400 text-sm mb-2">AI Interview Score / 100</div>');
lines.push('              <span className={"inline-block px-4 py-1.5 rounded-full text-sm font-bold mb-3 " + (report.score >= 75 ? "bg-green-500/15 text-green-600" : report.score >= 50 ? "bg-amber-500/15 text-amber-600" : "bg-red-500/15 text-red-600")}>Grade: {report.grade}</span>');
lines.push('              <p className="text-slate-700 dark:text-slate-300 font-medium">{report.verdict}</p>');
lines.push('              <div className="w-full h-3 bg-slate-200 dark:bg-slate-700 rounded-full mt-4 overflow-hidden">');
lines.push('                <div className={"h-full rounded-full transition-all duration-1000 " + (report.score >= 75 ? "bg-green-500" : report.score >= 50 ? "bg-amber-500" : "bg-red-500")} style={{ width: report.score + "%" }} />');
lines.push('              </div>');
lines.push('            </div>');
lines.push('');
lines.push('            {mlMetrics && mlMetrics.totalSamples > 0 && (');
lines.push('              <div className="rounded-[2rem] border border-blue-500/20 bg-blue-500/5 p-6">');
lines.push('                <div className="flex items-center gap-2 mb-5">');
lines.push('                  <Camera className="w-5 h-5 text-blue-500" />');
lines.push('                  <h3 className="text-blue-600 dark:text-blue-400 font-bold">Body Language Analysis</h3>');
lines.push('                  <span className="ml-auto text-xs bg-blue-500/15 text-blue-500 px-2.5 py-1 rounded-full border border-blue-500/20">ML Powered</span>');
lines.push('                </div>');
lines.push('                <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">');
lines.push('                  {[');
lines.push('                    { label: "Eye Contact", val: mlMetrics.avgEyeContact, icon: "???" },');
lines.push('                    { label: "Posture", val: mlMetrics.avgPosture, icon: "??" },');
lines.push('                    { label: "Confidence", val: mlMetrics.avgConfidence, icon: "??" },');
lines.push('                    { label: "Body Language", val: mlMetrics.bodyLanguageScore, icon: "?" },');
lines.push('                  ].map(({ label, val, icon }) => (');
lines.push('                    <div key={label} className={"rounded-2xl border p-4 text-center " + (val >= 70 ? "bg-green-500/5 border-green-500/20" : val >= 40 ? "bg-amber-500/5 border-amber-500/20" : "bg-red-500/5 border-red-500/20")}>');
lines.push('                      <div className="text-2xl mb-1">{icon}</div>');
lines.push('                      <div className={"text-3xl font-black " + (val >= 70 ? "text-green-500" : val >= 40 ? "text-amber-500" : "text-red-500")}>{val}%</div>');
lines.push('                      <div className="text-slate-400 text-xs mt-1">{label}</div>');
lines.push('                      <div className="w-full h-1.5 bg-slate-200 dark:bg-slate-700 rounded-full mt-2 overflow-hidden">');
lines.push('                        <div className={"h-full rounded-full " + (val >= 70 ? "bg-green-500" : val >= 40 ? "bg-amber-500" : "bg-red-500")} style={{ width: val + "%" }} />');
lines.push('                      </div>');
lines.push('                    </div>');
lines.push('                  ))}');
lines.push('                </div>');
lines.push('                <div className="grid md:grid-cols-2 gap-4">');
lines.push('                  <div className="bg-white/50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-4">');
lines.push('                    <p className="text-slate-600 dark:text-slate-400 text-xs font-semibold mb-2">Look Away Count</p>');
lines.push('                    <p className={"text-2xl font-black " + (mlMetrics.lookAwayCount < 5 ? "text-green-500" : mlMetrics.lookAwayCount < 15 ? "text-amber-500" : "text-red-500")}>{mlMetrics.lookAwayCount}</p>');
lines.push('                    <p className="text-slate-400 text-xs mt-1">{mlMetrics.lookAwayCount < 5 ? "Excellent eye contact!" : mlMetrics.lookAwayCount < 15 ? "Decent, try to maintain more" : "Try to look at camera more"}</p>');
lines.push('                  </div>');
lines.push('                  <div className="bg-white/50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-4">');
lines.push('                    <p className="text-slate-600 dark:text-slate-400 text-xs font-semibold mb-2">Dominant Expression</p>');
lines.push('                    <p className="text-2xl font-black text-blue-500 capitalize">{Object.entries(mlMetrics.expressionCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "neutral"}</p>');
lines.push('                    <p className="text-slate-400 text-xs mt-1">Most frequent during interview</p>');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('                <div className="mt-4 p-3 bg-white/50 dark:bg-white/5 rounded-2xl border border-slate-200 dark:border-white/10">');
lines.push('                  <p className="text-slate-500 text-xs">Tracked {mlMetrics.totalSamples} frames over {fmt(timer)} interview duration</p>');
lines.push('                </div>');
lines.push('              </div>');
lines.push('            )}');
lines.push('');
lines.push('            <div className="grid md:grid-cols-2 gap-5">');
lines.push('              <div className="bg-green-500/5 border border-green-500/20 rounded-2xl p-5">');
lines.push('                <div className="flex items-center gap-2 mb-4"><CheckCircle className="w-4 h-4 text-green-500" /><h3 className="text-green-600 font-bold text-sm uppercase tracking-wider">Strengths</h3></div>');
lines.push('                {(report.strengths || []).map((s: string, i: number) => (');
lines.push('                  <div key={i} className="flex items-start gap-2 mb-3 bg-green-500/5 rounded-xl p-3">');
lines.push('                    <span className="text-green-500 font-bold flex-shrink-0">+</span>');
lines.push('                    <p className="text-slate-700 dark:text-slate-300 text-sm">{s}</p>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('              <div className="bg-red-500/5 border border-red-500/20 rounded-2xl p-5">');
lines.push('                <div className="flex items-center gap-2 mb-4"><AlertCircle className="w-4 h-4 text-red-500" /><h3 className="text-red-600 font-bold text-sm uppercase tracking-wider">Improve</h3></div>');
lines.push('                {(report.weaknesses || []).map((w: string, i: number) => (');
lines.push('                  <div key={i} className="flex items-start gap-2 mb-3 bg-red-500/5 rounded-xl p-3">');
lines.push('                    <span className="text-red-500 font-bold flex-shrink-0">-</span>');
lines.push('                    <p className="text-slate-700 dark:text-slate-300 text-sm">{w}</p>');
lines.push('                  </div>');
lines.push('                ))}');
lines.push('              </div>');
lines.push('            </div>');
lines.push('');
lines.push('            <div className="bg-slate-50 dark:bg-white/5 border border-slate-200 dark:border-white/10 rounded-2xl p-5">');
lines.push('              <h3 className="text-slate-900 dark:text-white font-bold mb-4 text-sm uppercase tracking-wider flex items-center gap-2"><TrendingUp className="w-4 h-4 text-violet-500" />Topic Performance</h3>');
lines.push('              {(report.topic_scores || []).map((t: any, i: number) => (');
lines.push('                <div key={i} className="mb-3">');
lines.push('                  <div className="flex justify-between text-sm mb-1">');
lines.push('                    <span className="text-slate-600 dark:text-slate-300 font-medium">{t.topic}</span>');
lines.push('                    <span className={"font-bold " + (t.score >= 75 ? "text-green-500" : t.score >= 50 ? "text-amber-500" : "text-red-500")}>{t.score}%</span>');
lines.push('                  </div>');
lines.push('                  <div className="w-full h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">');
lines.push('                    <div className={"h-full rounded-full " + (t.score >= 75 ? "bg-green-500" : t.score >= 50 ? "bg-amber-500" : "bg-red-500")} style={{ width: t.score + "%" }} />');
lines.push('                  </div>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('');
lines.push('            <div className="bg-amber-500/5 border border-amber-500/20 rounded-2xl p-5">');
lines.push('              <h3 className="text-amber-600 font-bold mb-4 text-sm uppercase tracking-wider">Tips to Improve</h3>');
lines.push('              {(report.tips || []).map((t: string, i: number) => (');
lines.push('                <div key={i} className="flex items-start gap-2 mb-3">');
lines.push('                  <span className="text-amber-500 font-bold text-sm flex-shrink-0">{i + 1}</span>');
lines.push('                  <p className="text-slate-700 dark:text-slate-300 text-sm">{t}</p>');
lines.push('                </div>');
lines.push('              ))}');
lines.push('            </div>');
lines.push('');
lines.push('            <div className="bg-violet-500/5 border border-violet-500/20 rounded-2xl p-5">');
lines.push('              <h3 className="text-violet-600 font-bold mb-2 text-sm uppercase tracking-wider flex items-center gap-2"><Award className="w-4 h-4" />Next Steps</h3>');
lines.push('              <p className="text-slate-700 dark:text-slate-300 text-sm">{report.next_steps}</p>');
lines.push('            </div>');
lines.push('');
lines.push('            <div className="flex gap-3">');
lines.push('              <button onClick={reset} className="flex-1 bg-violet-600 hover:bg-violet-500 text-white font-semibold py-3 rounded-2xl text-sm transition-all flex items-center justify-center gap-2">');
lines.push('                <RotateCcw className="w-4 h-4" />Try Another Domain');
lines.push('              </button>');
lines.push('              <button onClick={() => domain && startInterview(domain)} className="flex-1 border border-slate-200 dark:border-white/10 text-slate-600 dark:text-slate-300 font-semibold py-3 rounded-2xl text-sm hover:border-violet-500/40 transition-all flex items-center justify-center gap-2">');
lines.push('                <RotateCcw className="w-4 h-4" />Retry Same Domain');
lines.push('              </button>');
lines.push('            </div>');
lines.push('          </div>');
lines.push('        )}');
lines.push('      </div>');
lines.push('    </AppShell>');
lines.push('  );');
lines.push('}');

fs.writeFileSync(path, lines.join("\n"), "utf8");
console.log("Video Interview page created!");
